language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
# install: "pip install -r requirements.txt --use-mirrors"
# # command to run tests
install:
 - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
 - pip install tox
before_script:
 - "rm -f __init__.py"
 - "rm -f __init__.pyc"
 - sudo apt-get install -qq libmysqlclient-dev

script:
 - tox

notifications:
  email: false
